name: Prebuild Codespaces

# **What it does**: Prebuild the Codespaces image using powerful machines.
#   See https://github.com/github/codespaces-precache#readme for more details.
#   IMPORTANT: Requires we set a `EXPERIMENTAL_CODESPACE_CACHE_TOKEN` Codespaces
#   Secret (NOT an Actions Secret) in the repository.
# **Why we have it**: Reduces startup time when booting Codespaces.
# **Who does it impact**: Any Docs contributors who want to use Codespaces.

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Currently requires write, but in the future will only require read
permissions:
  contents: write

jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: github/codespaces-precache@2ad40630d7e3e45e8725d6a74656cb6dd17363dc
        with:
          regions: WestUs2 EastUs WestEurope SouthEastAsia
          sku_name: basicLinux32gb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
